name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --collect:"XPlat Code Coverage" 
    - uses: codecov/codecov-action@v1
      with:
        token: CODECOV_TOKEN='4b9e2b9c-5792-4d63-94cc-b6d5faa3e1e6'
        files: ./CustomClassLibraryTests1/TestResults/*/coverage.cobertura.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci-if_error: true
        verbose: true
  
